### ISSUE TITLE
Outdated versions

### ISSUE THREAD

**Issue by Mansour-J** [Mbarmem/Grafana.Dashboard#2]
Hi is the docker versions are still applicable to this setup? 

Influx db latest image is version 2 and it is not working, same as telegraf....

Would you be able to specify what version was being used for the containers?

**Comment by bcordy3** [comment]
My friend and I timematched the app versions with when the most recent updates to this setup were pushed. The apps run instead of failing entirely like they were before, but the webpage for influx DB won't load. Versions we used via matching and set up in docker-compose.yml:
Influxdb versioning: image: influxdb:1.8.2
Telegraf versioning: image: telegraf:1.15.3

Before making these changes, influxdb and telegraf would bootloop within docker, after the version changes they start up and turn green, but still have other issues like the influxdb webpage not loading up. If anyone has any solutions for this please let me know, docker is super dense and the instructions on this github are very sparse and assume you know very much about docker. Very hard to proceed when everything in the setup is broken - Cannot get to configuring grafana since the initial infrastructure will not spin up properly.

**Comment by Mbarmem** [comment]
Hey, sorry for the delay.

I'll be updating this in the coming week with updated versions and tweaks.

**Comment by bcordy3** [comment]
Hi Mbarmem,

No worries! Have you been able to successfully apply the updated versions and tweaks? I will try this project again once that's confirmed - Thank you very much for your work on this!

**Comment by Mbarmem** [comment]
Version have been updated earlier. Everything should be working now.
